apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trust-bundle.yaml

secretGenerator:
  - name: root-ca
    namespace: cert-manager
    files:
      - ca.crt=ca.crt
    type: Opaque
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "0"

generatorOptions:
  disableNameSuffixHash: true