apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pki-resources-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: default

  source:
    repoURL: https://github.com/Mariozdz/vault-tec.git
    targetRevision: main
    path: infrastructure/pki/overlays/lab

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true