apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-bundles-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default

  source:
    repoURL: git@github.com:Mariozdz/vault-tec.git
    targetRevision: main
    path: infrastructure/trust-manager/bundles/overlays/lab

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true