apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nebula-vault-gateway
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:Mariozdz/vault-tec.git
    targetRevision: main
    path: infrastructure/nebula/overlays/lab

  destination:
    server: https://kubernetes.default.svc
    namespace: nebula

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true