apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-lab
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/Mariozdz/vault-tec.git
    targetRevision: main
    path: infrastructure/namespaces/overlays/lab
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true