apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-apiserver-access.yaml
  - argocd-dns-access.yaml
  - argocd-github-access.yaml
  - argocd-helm-access.yaml
  - argocd-internal-access.yaml